llm:
  base_url: "http://localhost:9001/v1"
  model_name: "Qwen3.5"
  temperature: 0.3

target_sources: 50
max_steps: 50
target_datasets: 30
rescrape_steps: 5

dataset_goal: "leukocyte / white blood cell labeled datasets for segmentation, classification and identification"

# it is crucial to keep the variables within the curly braces {vars} as these use runtime 
# variables to limit the search of the model.
prompts:
  discovery_human: |
    Search for datasets about {dataset_goal} and return the results when you find 5.